import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('pharmaboard.access_token','appearance-preview-only');});
await page.route('**/v1/**',async route=>{
 const path=new URL(route.request().url()).pathname;
 const body=path.endsWith('/auth/me')?{id:'00000000-0000-4000-8000-000000000001',display_name:'Ama Mensah',account_kind:'student',verification_state:'unverified'}:path.endsWith('/messaging/unread')?{count:0,items:[]}:{items:[],next_cursor:null};
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
});
await page.goto(`${process.env.PREVIEW_URL || 'http://127.0.0.1:5174'}/settings`);
await page.getByRole('heading',{name:'Your space. Your style.'}).waitFor();
await page.getByRole('button',{name:/Sunset Berry/}).click();
await page.getByRole('button',{name:/Rounded Friendly/}).click();
await page.getByLabel('Text size').selectOption('comfortable');
await page.reload();
await page.getByRole('heading',{name:'Your space. Your style.'}).waitFor();
assert.equal(await page.getByRole('button',{name:/Sunset Berry/}).getAttribute('aria-pressed'),'true');
assert.equal(await page.getByLabel('Text size').inputValue(),'comfortable');
assert.match(await page.evaluate(()=>getComputedStyle(document.body).fontFamily),/Avenir/);
assert.equal(await page.getByRole('button',{name:'Try the look'}).evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(185, 49, 101)');
await page.screenshot({path:'/tmp/pharmaboard-appearance-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'/tmp/pharmaboard-appearance-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Reset appearance'}).click();
assert.equal(await page.getByLabel('Text size').inputValue(),'standard');
assert.deepEqual(errors,[]);
await browser.close();console.log('PASS palette, font, text size, persistence, reset and mobile overflow (mocked API)');
