import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const email=`browser-${Date.now()}@example.com`;
await page.goto('http://127.0.0.1:5174/notices');
await page.getByRole('button',{name:'Create an account',exact:true}).click();
await page.getByLabel('Full name',{exact:true}).fill('Akosua Boateng');
await page.getByLabel('School or organisation').fill('University of Ghana');
await page.getByLabel('Email address').fill(email);
await page.getByLabel('Password',{exact:true}).fill('a memorable secure phrase');
await page.screenshot({path:'/tmp/auth-signup-desktop.png'});
await page.getByRole('button',{name:'Create account',exact:true}).click();
await page.waitForURL('**/notices');
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.getByLabel('Email address').fill(email);
await page.getByLabel('Password',{exact:true}).fill('wrong password');
await page.getByRole('button',{name:'Sign in',exact:true}).click();
await page.getByRole('alert').waitFor();
await page.getByLabel('Password',{exact:true}).fill('a memorable secure phrase');
await page.getByRole('button',{name:'Sign in',exact:true}).click();
await page.waitForURL('**/notices');
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.getByLabel('Email address').waitFor();
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'/tmp/auth-login-mobile.png'});
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS signup, preserved destination, logout, wrong-password error, login, mobile layout; fixture email: '+email);
