import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5174/sessions?code=0000-0000-0300');await page.getByRole('button',{name:'Explore sample workspace'}).click();await page.getByRole('dialog').getByLabel('Meeting code').waitFor();assert.equal(await page.getByLabel('Meeting code').inputValue(),'0000-0000-0300');await page.keyboard.press('Escape');await page.goto('http://127.0.0.1:5174/home');await page.getByRole('heading',{name:/Good to see you/}).waitFor();
for(const route of ['home','learning','jobs','sessions','messaging','notices']){await page.goto('http://127.0.0.1:5174/'+route);await page.locator('h1').waitFor();await page.waitForTimeout(350);await page.screenshot({path:`/tmp/pharmaboard-workspace-qa/final-${route}.png`});assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await page.goto('http://127.0.0.1:5174/learning');assert.equal(await page.getByRole('button',{name:'Share a lesson',exact:true}).evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(36, 99, 212)');await page.getByRole('button',{name:'The art of the patient consultation',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.locator('iframe').count(),0);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:5174/learning');await page.locator('h1').waitFor();await page.screenshot({path:'/tmp/pharmaboard-workspace-qa/final-mobile-learning.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);await browser.close();console.log('PASS invitation preserved through login, six populated screens, exact blue-and-white colors, sample-media distinction, keyboard dialogs, mobile width');
