import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const API='http://localhost:8081/v1';
async function req(path,method='GET',body,token,status=200){const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});assert.equal(r.status,status,`${method} ${path}`);const text=await r.text();return text?JSON.parse(text):null;}
async function login(n){const contact=`+23320088000${n}`;const otp=await req('/auth/otp/request','POST',{channel:'phone',contact},undefined,202);assert(otp.dev_only_code);const session=await req('/auth/otp/verify','POST',{channel:'phone',contact,code:otp.dev_only_code});return {token:session.access_token,user:await req('/auth/me','GET',undefined,session.access_token)};}
const a=await login(1),b=await login(2);const id=crypto.randomUUID();const entry={kind:'project',title:'Portfolio integrity check',organization:'Local QA',period:'2026',description:'Temporary test entry',url:'https://example.com'};
await req(`/workspace/portfolio/${id}`,'PUT',entry,a.token);await req(`/workspace/portfolio/${id}`,'PUT',entry,b.token,403);await req(`/workspace/portfolio/${id}`,'DELETE',undefined,b.token,404);await req(`/workspace/portfolio/${crypto.randomUUID()}`,'PUT',{...entry,url:'javascript:alert(1)'},a.token,400);assert((await req(`/workspace/profiles/${a.user.id}`,'GET',undefined,b.token)).entries.some(e=>e.id===id));
const before=await req(`/workspace/profiles/${a.user.id}`,'GET',undefined,a.token);await req('/workspace/profile/learning-visibility','PUT',{visible:false},a.token,204);assert.deepEqual((await req(`/workspace/profiles/${a.user.id}`,'GET',undefined,b.token)).learning,[]);await req('/workspace/profile/learning-visibility','PUT',{visible:true},a.token,204);assert.deepEqual((await req(`/workspace/profiles/${a.user.id}`,'GET',undefined,b.token)).learning,before.learning);await req('/workspace/profile/learning-visibility','PUT',{visible:before.learning_visible},a.token,204);await req(`/workspace/portfolio/${id}`,'DELETE',undefined,a.token,204);
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5174/learning');await page.getByRole('button',{name:'Explore sample workspace'}).click();await page.getByRole('button',{name:'Collapse sidebar',exact:true}).click();assert.equal(await page.locator('#workspace-navigation').isVisible(),false);await page.reload();await page.getByRole('button',{name:'Expand sidebar',exact:true}).waitFor();await page.goto(`http://127.0.0.1:5174/people/${a.user.id}`);await page.getByRole('button',{name:'Expand sidebar',exact:true}).click();await page.getByRole('button',{name:'Add projects',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Browser portfolio check');await page.getByLabel('Description',{exact:true}).fill('A temporary project used to check profile editing.');await page.getByRole('button',{name:'Save entry',exact:true}).click();await page.getByRole('heading',{name:'Browser portfolio check',exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'Browser portfolio check',exact:true}).waitFor();await page.getByRole('button',{name:'Edit Browser portfolio check',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Edited portfolio check');await page.getByRole('button',{name:'Save entry',exact:true}).click();await page.getByRole('button',{name:'Remove Edited portfolio check',exact:true}).click();await page.getByRole('button',{name:'Remove entry',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.getByRole('heading',{name:'Edited portfolio check',exact:true}).count(),0);await page.screenshot({path:'/tmp/pharmaboard-workspace-qa/profile-desktop.png'});await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation',exact:true}).click();assert(await page.locator('#workspace-navigation').isVisible());await page.getByRole('button',{name:'Close navigation',exact:true}).last().click();await page.waitForTimeout(350);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/pharmaboard-workspace-qa/profile-mobile.png'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS owner authorization, safe links, learning visibility, profile CRUD persistence, sidebar persistence, mobile navigation');
