// Development-only, explicitly labeled sample content for design review.
const API=process.env.PHARMABOARD_API_BASE||'http://localhost:8081/v1';
if(!['localhost','127.0.0.1'].includes(new URL(API).hostname))throw new Error('Preview seeding is restricted to a local development API');
async function req(path,method='GET',body,token){const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();const data=t?JSON.parse(t):null;if(!r.ok&&r.status!==409)throw new Error(`${method} ${path}: ${r.status} ${data?.detail??''}`);return data;}
async function person(name,n,kind='pharmacist') {const phone=`+23320088000${n}`;await req('/auth/register','POST',{account_kind:kind,display_name:name,phone_e164:phone});const otp=await req('/auth/otp/request','POST',{channel:'phone',contact:phone});if(!otp.dev_only_code)throw new Error('Preview requires development OTP mode');const s=await req('/auth/otp/verify','POST',{channel:'phone',contact:phone,code:otp.dev_only_code});return {token:s.access_token,user:await req('/auth/me','GET',undefined,s.access_token)};}
const people=await Promise.all([person('Alex Morgan · Preview',1),person('Ama Boateng · Preview',2),person('Daniel Mensah · Preview',3),person('Nana Owusu · Preview',4,'student')]);
const owner=people[0];
const lessons=[['The art of the patient consultation','Clinical pharmacy','A practical framework for clearer conversations','01:00 Setting the scene\n05:30 Asking better questions\n12:00 Putting learning into practice'],['From evidence to everyday practice','Research','Build confidence reading the literature','00:00 Introduction\n04:00 Study design\n11:00 Discussing the evidence'],['Leading your first pharmacy team','Leadership','People, priorities, and purposeful leadership','00:00 Welcome\n03:00 Building a team\n09:00 Feedback that helps'],['Designing your professional path','Career development','Make room for the work you want to do','00:00 Reflection\n04:00 Exploring opportunities\n10:00 Your next steps']];
const jobs=[['Clinical Pharmacist','Full-time','Accra · On-site','Sample Teaching Hospital'],['Graduate Research Fellowship','Fellowship','Kumasi · Hybrid','Sample Research Institute'],['Pharmacy Practice Intern','Internship','Cape Coast · On-site','Sample Community Pharmacy'],['Medical Content Specialist','Remote','Ghana · Remote','Sample Health Education Studio']];
let count=0;
for(let i=0;i<lessons.length;i++){const [title,category,subtitle,chapters]=lessons[i];await req(`/workspace/00000000-0000-4000-8000-00000000010${i}`,'PUT',{kind:'learning',title,category,organization:'PharmaBoard Academy · Sample',description:`Preview lesson — illustrative content for design review.\n\n${subtitle}. This sample is not accredited clinical guidance.\n\n${chapters}`,url:'https://www.youtube.com/watch?v=jfKfPfyJRdk',location:''},owner.token);count++;}
for(let i=0;i<jobs.length;i++){const [title,category,location,organization]=jobs[i];await req(`/workspace/00000000-0000-4000-8000-00000000020${i}`,'PUT',{kind:'jobs',title,category,organization,location,description:'SAMPLE OPPORTUNITY — this is placeholder content, not an active vacancy.\n\nJoin a collaborative team committed to professional development and high-quality pharmacy practice. The role combines practical work, learning, and peer collaboration.\n\nIdeal profile: curiosity, clear communication, and a commitment to evidence-informed practice. Replace this description with a verified employer listing before publishing.',url:'https://example.com'},owner.token);count++;}
const sessions=[['The Sunday Journal Club','Journal club','A shared conversation about reading research critically.'],['Early-career peer circle','Study group','Compare notes, ask questions, and plan your next professional steps.'],['Community pharmacy roundtable','Team meeting','Connect with peers to discuss professional practice and community education.']];
for(let i=0;i<sessions.length;i++){const [title,category,description]=sessions[i];await req(`/workspace/00000000-0000-4000-8000-00000000030${i}`,'PUT',{kind:'sessions',title,category,organization:'Community learning · Sample',location:'',starts_at:new Date(Date.now()+(i+2)*86400000).toISOString(),url:`https://meet.jit.si/PharmaBoard-preview-${crypto.randomUUID()}`,description:`Preview session — not a real scheduled event.\n\n${description}\n\nAgenda\n• Introductions and goals\n• Shared discussion\n• Takeaways and next steps`},owner.token);count++;}
const posts=['A small habit that has made a big difference: setting aside 20 minutes each week to discuss a research paper with colleagues. What does your learning routine look like?','Professional growth is rarely a solo project. This week, I’m making time to reconnect with a mentor and share one useful resource with someone earlier in their journey.','We’re exploring what a better transition from university to practice could look like. Students and recent graduates: what support would have helped you most?'];
for(let i=1;i<people.length;i++){const person=people[i];const profile=await req(`/community/people/${person.user.id}`,'GET',undefined,person.token);if(profile.stats.posts===0)await req('/community/feed','POST',{body:posts[i-1]+'\n\n[Sample discussion for platform preview]'},person.token);}
const existing=(await req('/messaging/conversations','GET',undefined,owner.token)).items;
if(!existing.some(c=>c.title==='Clinical learning circle · Sample')){const c=await req('/messaging/conversations','POST',{participant_ids:people.slice(1).map(p=>p.user.id),title:'Clinical learning circle · Sample'},owner.token);await req(`/messaging/conversations/${c.id}/messages`,'POST',{body:'Welcome to this sample team space. Use the conversation to share ideas, the shared-links tab to collect resources, and Video call to meet in PharmaBoard.'},people[1].token);await req(`/messaging/conversations/${c.id}/messages`,'POST',{body:'For our preview discussion: https://example.com/learning-agenda'},owner.token);}
const title='How do you build a useful journal club? · Sample';const threads=await req('/community/forum?q='+encodeURIComponent(title),'GET',undefined,owner.token);if(!threads.items.length)await req('/community/forum','POST',{title,body:'Sample discussion: We are putting together a peer learning group. What structure helps everyone contribute and leave with a practical takeaway?',tags:['learning','research']},people[1].token);
console.log(`Seeded ${count} labeled preview resources, sample colleagues, community discussions, and a team conversation.`);
